### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by diegoponciano** [ksachdeva/angular2-swing#1]
Hi, I'm new to Angular2, and I'm trying to figure out how to use this component on a project.

I also never used Swing, but I use a similar component in a Ionic v1 application: https://github.com/xchilenox/ionic-tinder-cards.

**Comment by asgarddesigns** [comment]
Agreed, some idea on how this can be implemented would be appreciated!

Are you still using this lib @ksachdeva or have you found a better alternative?

**Comment by ksachdeva** [comment]
Will update the repo and post an example showing how to use it over the weekend. Sorry for the delay.

**Comment by alexciesielski** [comment]
Hi, any news on the docs? 

Woud like to use these cards with ng2.

Thanks

**Comment by ksachdeva** [comment]
sorry for long delay. have updated the component for angular 2 and there is an example repository that shows how to use it https://github.com/ksachdeva/angular2-swing-example
