### ISSUE TITLE
Does not compile for AoT

### ISSUE THREAD

**Issue by cjdreiss** [ksachdeva/angular2-swing#12]
You need to include some new stuff in the tsconfig file for AoT https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

I'm working on a pull request on my fork right now, making an issue to ref in the pull request.  I also included the changes from #11 in my fork, since I needed that for my Ionic project.

**Comment by ksachdeva** [comment]
Thanks for the pull requests
