### ISSUE TITLE
Thrown out cards remain in DOM though not visible

### ISSUE THREAD

**Issue by florianbepunkt** [ksachdeva/angular2-swing#15]
Hi, thank you for this plugin.

I'm using it in a mobile application I'm developing. I experience the following issue: some of my cards remain in DOM after they have been swiped left or right. they are not visibile but remain in dom nonetheless. they have the following transform css inline style

`transform: translate3d(0px, 0px, 0px) translate(500px, 0px) rotate(0deg);
`
where 500px equals my thrownout distance. I dnynamically fetch new cards when the stack falls below a certain threshold. this behviour appears rather randomly, not on all cards. 

**exspected behaviour:**
Swiped cards are removed from stack and dom

**actual behaviour:**
some cards remain in stack/DOM although not visible

Can you help?

**Comment by nukkerone** [comment]
Did you find a solution for that? 
It is also happening to me and not sure how to correct it.

**Comment by florianbepunkt** [comment]
As far as I remember I was playing with throwOutConfidence and  throwOutDistance values until cards were thrown out for sure. But haven't done much testing with this yet.

**Comment by nukkerone** [comment]
I ended up fetching data for 20 cards at a time, but adding/removing one by one to avoid this issue.

**Comment by florianbepunkt** [comment]
How did you add / remove the cards one by one?

**Comment by nukkerone** [comment]
What I meant is that my service returns data for 20 items at the same time, but instead of adding all at once to the stack doing like the following:

```javascript
for (let val of result) { // Adds all
    this.cards.push(val);
}
```

Im just adding the first one:

```javascript 
this.cards.push(result[0]); // Adds first
```

Then on swipe (voteUp) I remove that one, and push the next one:
```javascript
voteUp(type) {
    let removedCard = this.cards.pop();
    this.cards.push(result[1]);   // Index is hardcoded, but you'll get the idea
}
```

Does that makes sense? Just wanted to avoid having multiple cards rendered at the same time because of the problem you mentioned. Not optimal but makes the job for me.

**Comment by florianbepunkt** [comment]
Totally makes sense, but UI wise it would be nice to have at least two cards in order to see the bottom card while swiping the upper one. I hope I can do some tests later this week, but basically this is my stack.config

```
this.stackConfig = {
		  throwOutConfidence: (offset, element) => {
		    // return Math.min(Math.abs(offset) / (element.offsetWidth/2), 1);
            return Math.min(Math.abs(offset) / (element.offsetWidth/3), 1);
		  },
		  transform: (element, x, y, r) => {
		    this.onItemMove(element, x, y, r);
		  },
		  throwOutDistance: (d) => {
		    return 700;
		  }
		};
```

**Comment by numerized** [comment]
Have you been able to lazy load cards at the back of the stack ?? no matter what I do the card appear at the top of the stack and it's very annoying ...

no matter if I push or pop the next card appear on top of the existing one...

**Comment by florianbepunkt** [comment]
@numerized Try with an track by function in your ng repeat, so cards alreay in the stack don't get rerendered, when cards array changes. You can read up about it here: https://docs.angularjs.org/api/ng/directive/ngRepeat

> To minimize creation of DOM elements, ngRepeat uses a function to "keep track" of all items in the collection and their corresponding DOM elements. For example, if an item is added to the collection, ngRepeat will know that all other items already have DOM elements, and will not re-render them.

If i remember correctly, thecards stack renders your cards array bottom up, so last element of your array is the top card. So make sure you prepend your newly fetches cards instead of appending them to the end of your array.

**Comment by numerized** [comment]
yes that's an excellent idea I'll try this ! thanks

**Comment by jayordway** [comment]
Was there any resolution to this, I still have the problem with trackBy function and prepending the cards?
