### ISSUE TITLE
make cards throwable in 4 directions

### ISSUE THREAD

**Issue by baskin** [ksachdeva/angular2-swing#16]
Gajus swing now supports throwing in all 4 directions via:
https://github.com/gajus/swing/commit/81045acbb88fb64e69fa0c2220693858c22457cf

Can we also support the same?

Thanks,

**Comment by PrithiviRajG** [comment]
are we having any idea to implement the same?
I want to add swipe down feature in my app addition to left and right

**Comment by mashhoodr** [comment]
Added support here: https://github.com/ksachdeva/angular2-swing/pull/19

Current issue is latest version of swing on npm is not working. So you need to manually clone and build that if you need this.

**Comment by mashhoodr** [comment]
Fixed by merging https://github.com/ksachdeva/angular2-swing/pull/19
