### ISSUE TITLE
Stack ordering issue

### ISSUE THREAD

**Issue by btroncone** [ksachdeva/angular2-swing#24]
Hello,

Great work on this library, and thanks for the recent update!

I have a question regarding stack order.

I have a card stack in which I am adding and removing cards, both through gestures and programmatically as the user clicks buttons. This is an example of the html content.

![image](https://cloud.githubusercontent.com/assets/5085101/24523641/ba41aa54-1561-11e7-9643-96b5def1b37c.png)

When using programmatically everything works fine, cards slide in and out of their position correctly. The issue is when I combine swiping with throwing in / out programmatically. The DOM updates and the order becomes lost. When I then `throwIn` to the deck programmatically , the cards slide under instead of over in some instances. Below is an example of what the HTML content looks like in this scenario, after a few gestures + `throwIn`. You can see element `1` has moved above element `2`, so element `1` then slides under `2` instead of on top when I throw back in.

![image](https://cloud.githubusercontent.com/assets/5085101/24523909/ad28e1d8-1562-11e7-8936-21674ff920d2.png)

Any suggestions you can give to fix this problem would be greatly appreciated. I'm currently spinning my wheels. Thanks in advance for the help or ideas! 😄

**Comment by mashhoodr** [comment]
@btroncone this feels like a problem in the swing library, I dont think the wrapper is interfering with the DOM.

**Comment by btroncone** [comment]
Think you're right, I have been digging through the code and believe I found the issue. I'm going to close this but will add a comment explaining fix if others encounter the same issue. Thanks!

**Comment by btroncone** [comment]
For those interested, this line is the culprit in `card.js`. This was manually reordering DOM when combining programmatic updates with manual swiping, causing stack ordering issues. Comment out to fix.

Card.appendToParent = (element) => {
  const parentNode = element.parentNode;
  const siblings = elementChildren(parentNode);
  const targetIndex = siblings.indexOf(element);
  // comment this out and order is maintained
  if (targetIndex + 1 !== siblings.length) {
       parentNode.removeChild(element);
       parentNode.appendChild(element);
   }
};
