### ISSUE TITLE
Importing SwingModule in Ionic3 freeze scrolls if (swipe) is used

### ISSUE THREAD

**Issue by peterpeterparker** [ksachdeva/angular2-swing#26]
Hey,

It looks like that importing SwingModule in a Ionic 3 project as a weird side effect.

If somewhere in the application you use the event (swipe) on a list or a scroll, then that list or scroll gonna be frozen respectively not scrollable on both iOS and Android devices.

If you remove the import of the SwingModule, then the scroll and list work as excepted.

For example:

    <ion-scroll #datePickerScrollY scrollY="true" id="datePickerScrollY">
        <ion-list no-padding (swipe)="swipeSomething($event)"> 
            <ion-item *ngFor="let hero of heroes;">
                <p>
                    {{hero.name}}
                </p>
            </ion-item>
        </ion-list>
    </ion-scroll>

There is a sample project to reproduce the problem:

https://github.com/peterpeterparker/myIonScroll.git

Just by commenting SwingModule in app.module.ts gonna make the list scrollable.

Any idea how to solve that issue?

P.S.: A screenshot too

<img width="378" alt="capture d ecran 2017-04-19 a 16 40 51" src="https://cloud.githubusercontent.com/assets/16886711/25186054/48187da4-251f-11e7-93a3-6537e1af428e.png">

**Comment by peterpeterparker** [comment]
Looks like the problem is related to hammerjs. Including SwingModule will load swing.js which load hammerjs which lead to the problem.

**Comment by kapilSoni101** [comment]
hi sir i am not using any SwingModule  in our app.i have scrolling issue in iphone7 as well as screen are freeze but in the iphoneX its working do you have any idea how to fix scrolling issue?

**Comment by mayankkataria** [comment]
I'm also facing the same issue without hammerjs.
