### ISSUE TITLE
Access thrown out card

### ISSUE THREAD

**Issue by Shehab-Muhammad** [ksachdeva/angular2-swing#27]
Current api support `(throwout)` event but it's on `swing-stack` so I can't access thrown card at this point as `swing-stack` is a top level of `swing-card` where `*ngFor` exists.  

I need to access this card to do some logic not only `event` as an argument to the callback function.  

is this doable ?

**Comment by mashhoodr** [comment]
Hello @Shehab-Muhammad can you please create an example to show what you are looking for, didnt quite get whats exactly needed.

**Comment by mashhoodr** [comment]
@Shehab-Muhammad can we close this?

**Comment by Shehab-Muhammad** [comment]
tell me how to access card thrownout ?
I can access throw event only which is useless

**Comment by mashhoodr** [comment]
the throw event contains the card being thrown,its one of the property. You can log and check.

**Comment by Shehab-Muhammad** [comment]
card as component not my own data !
what can I do with this component I want to access my model that I'm looping through it inside the stack
