### ISSUE TITLE
No Directive annotation found on SwingStackComponent

### ISSUE THREAD

**Issue by rockertux** [ksachdeva/angular2-swing#3]
When including `SwingStackComponent` and `SwingCardComponent` in my Component's `directive` property, it fails to load with this error: `No Directive annotation found on SwingStackComponent` or `No Directive annotation found on SwingCardComponent`. Works on angular-2.0.0.rc.1, fails on angular-2.0.0.rc.3.

Is it a directive bug or an angular bug?

**Comment by ksachdeva** [comment]
hi @rockertux

**Comment by ksachdeva** [comment]
Hi rockertux,

Not able to reproduce. I believe it is webpack that creates such problems. try this example and see if you can reproduce - https://github.com/ksachdeva/angular2-swing-example

I have update the package to 0.5.0 that uses rc.4

**Comment by rockertux** [comment]
I'm trying this in a Ionic 2 beta-10 project. Just upgraded from beta-9, still no luck, with angular2-rc.4.

**Comment by numerized** [comment]
@ksachdeva I have the same problem with Ionic 2 beta-10, I was able to make it work with 2.0.0-beta.7 perfectly.

**Comment by anbu369** [comment]
same problem. with ionic 2 and rc4
