### ISSUE TITLE
how can i allow user to drag the card only in left and right direction not up and down 

### ISSUE THREAD

**Issue by ghost** [ksachdeva/angular2-swing#33]

**Comment by mba858** [comment]
any update for this issue?

**Comment by mashhoodr** [comment]
@mba858 you can use the allowedDirections property for this:
https://github.com/ksachdeva/angular2-swing-example/blob/master/src/app/app.component.ts#L28

**Comment by mba858** [comment]
@mashhoodr I set the allowedDirections, but still card is swiping for all directions even I set only left and right. Here's my config:

    this.stackConfig = {
      allowedDirections: [Direction.LEFT, Direction.RIGHT],
      throwOutConfidence: (offsetX, offsetY, element) => {
        return Math.min(Math.abs(offsetX) / (element.offsetWidth / 2), 1);
      },
      transform: (element, x, y, r) => {
        this.onItemMove(element, x, y, r);
      },
      throwOutDistance: (d) => {
        return 800;
      }
    };

**Comment by mba858** [comment]
@mashhoodr I checked the files and allowedDirections is only being taken but never used to restrict the movement of cards. Did you check that?

**Comment by vinitMundada** [comment]
this does not seem to work for me either, allowed directions is not restricting the user to swipe away cards in prohibited regions
