### ISSUE TITLE
swipe down

### ISSUE THREAD

**Issue by rangathedon** [ksachdeva/angular2-swing#40]
Is there any reason because of which swipe down cannot work? all other orientations are working well;

**Comment by mashhoodr** [comment]
Swipe down was working till last time, any chance you can create a plunkr to demo the issue? (stackblitz is pretty awesome for that)

**Comment by rangathedon** [comment]
I just used the basic example; I dont really know how to do thin in plunkr
or stachblitz;

On Thu, Oct 26, 2017 at 10:10 AM, Mashhood Rastgar <notifications@github.com

**Comment by rangathedon** [comment]
successfully made a stackblitz example; please check; 

demo can be seen at https://ionic-vcklfx.stackblitz.io/

code can be seen at https://stackblitz.com/edit/ionic-vcklfx?file=pages%2Fhome%2Fhome.html

**Comment by rangathedon** [comment]
got it working by adding the following in stackConfig in the TS file; I had tried specifying the same through html earlier and it had not worked;

      allowedDirections: [Direction.UP, Direction.DOWN, Direction.LEFT, Direction.RIGHT],

**Comment by Anujmoglix** [comment]
this is not working
