### ISSUE TITLE
No events triggered

### ISSUE THREAD

**Issue by anbu369** [ksachdeva/angular2-swing#5]
Hi I am using the plugin with ionic 2 angular 2. I can see the cards working fine. But how do I access the events. I dont see any events triggered in the console. thanks

**Comment by ksachdeva** [comment]
Hi @anbu369 you should be able to get the underlying stack field and then listen for events on that. That said, I see a pull request that will expose the events in more Angular 2 approach. Still for update in a day or two.

**Comment by numerized** [comment]
Hello have you progressed on this my friend ? Thanks for your work !

**Comment by ksachdeva** [comment]
Sincere apologies, got tied up.

Would get back to you on this very soon.

**Comment by numerized** [comment]
Thanks again, this time for fast reply !

**Comment by ksachdeva** [comment]
angular2-swing 0.5.0 has been released. please see the example (https://github.com/ksachdeva/angular2-swing-example) of how to use the events.

Will do few more updates today but wanted to release a version as it was long due. 

Apologies for the delay.

**Comment by ksachdeva** [comment]
Have released angular2-swing 0.6.0 which has more typings and features. Again check out the example. Hope you will like it.

**Comment by numerized** [comment]
Thanks that's working great, I've added it to ionic2 without any problem.
