### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by satanworker** [ksachdeva/angular2-swing#8]
after npm start webpage get 404 for all script files

**Comment by ksachdeva** [comment]
then most likely you do not have packages installed. Did you do npm install. May be node_modules got deleted by mistake. Please verify !

**Comment by satanworker** [comment]
here is a gif
![aug-28-2016 03-02-27](https://cloud.githubusercontent.com/assets/11026240/18030747/eb1751b8-6ccb-11e6-8af5-c7c44e0ae7fd.gif)

**Comment by satanworker** [comment]
node -v => v4.4.5

**Comment by ksachdeva** [comment]
seems like you are not getting the zone.js. could you try the latest release (have been upgraded to angular 2 final release)

**Comment by ksachdeva** [comment]
closing it for now; open if you still have the issue
